### ISSUE TITLE
这是一个不错的项目，期待作者能带领net core崛起

### ISSUE THREAD

**Issue by bbhxwl** [SmRiley/Socks5Server#1]
这是一个不错的项目，期待作者能带领net core崛起

**Comment by bbhxwl** [comment]
测试了一下udp会时不时的不通过。手动点击s5 测速，1秒大概点2次，基本就坏了
![QQ图片201912250051657](https://user-images.githubusercontent.com/26525599/71475453-37959780-281b-11ea-8516-58ad02f1be00.png)

**Comment by SmRiley** [comment]
抱歉抱歉,因为在限制UDP并发量上面为了突出效果用了试验性的同时3并发,已经重新上传了源码.此限制的代码行在Core/UDP_Listen.cs的Surplus_Count属性所控制.只是一个很简单的练手项目,我也只是学习而已.

**Comment by bbhxwl** [comment]
好吧，我以为大佬想要发扬光大，不错我们.net core 刚刚崛起，缺少很多不错的项目呢。希望大佬能维护。做的和https://github.com/justcoding121/Titanium-Web-Proxy      这个专门做http代理的sdk，很强大

**Comment by bbhxwl** [comment]
一直没找到好的.net 跨平台的socks5代理的代码。

**Comment by bbhxwl** [comment]
而且还是国人写的，难得哇。这个项目是不是如果不用账号密码认证系统的话，这就可以正常使用了。

**Comment by SmRiley** [comment]
开头几天我几乎找遍了中文网上的所有socks5代理资料.但是这些很偏的一点是大部分都忽略了UDP代理部分,然后对RFC1928的介绍都一知半解,并不像http有现成的轮子,.net Core将会成为最强的工业语言,但是这要走的还有很远.我目标是打算把这个写成一个轻量加密代理.绕过受限制的防火墙.我博客中有几篇介绍了关于这个项目的细节.[https://www.seeull.com/archives/24.html](url),不过我讲得有些啰嗦,加上可能经常性会鸽.

**Comment by SmRiley** [comment]
socks5的账号认证是没有任何安全保证的,ss里面的密码只是对称加密算法的密匙,所以并没有打算实现socks5本身的账户认证

**Comment by bbhxwl** [comment]
我觉得以前net 比不了python 主要是跨平台，目前感觉除了现成的轮子不多，都强过python啊。目前net  core 像proxy这种轮子，偏门的，还是少点。希望大佬能维护下去，比如增加个用户名密码验证的回调函数，比如每次数据处理的回调函数，能放弃返回（为了做ip地址限制）

**Comment by bbhxwl** [comment]
好吧，我本来是想要找一下ssr用.net core 开发的资料，奈何python代码超级多，还不懂socks5 协议的原理。

**Comment by bbhxwl** [comment]
socks5的账号认证是没有任何安全保证的，那就没办法限制完美了么？

**Comment by SmRiley** [comment]
这个后期就是为了实现类似早期ss的效果,关于这个你可以参考这篇[https://segmentfault.com/a/1190000011862912](url)文章.

**Comment by SmRiley** [comment]
关于这个密码就是加解密流的密匙(参考ss),如果校验正确可以解析正确的tcp流和udp包那么则建立正常代理,否则关闭连接即可.至于IP地址限制这个没有具体的想过.

**Comment by bbhxwl** [comment]
好吧，建议每个数据包弄个回调函数，方便二次开发，是比如有个canCancel=false  之类的就不调用内部的东西了。后面这个项目还会更新么。

**Comment by SmRiley** [comment]
是有这个的.至于canCancel这个是逻辑上的东西,你可以自定义,这个我觉得相比我最开始的已经算是比较精简了,应该不难懂.项目会一直更更新,后续我可能会考虑实现SSTAP的基础功能.

**Comment by bbhxwl** [comment]
> 是有这个的.至于canCancel这个是逻辑上的东西,你可以自定义,这个我觉得相比我最开始的已经算是比较精简了,应该不难懂.项目会一直更更新,后续我可能会考虑实现SSTAP的基础功能.

大佬对协议这方面这么了解么，sstap好像是虚拟网卡，通过socks5 经过自己程序转发成特定ssr之类的协议吧。sstap属于客户端，大佬的这个属于服务端。服务端最好是能验证帐号密码，之类的限制

**Comment by bbhxwl** [comment]
.net core现在也不适合做客户端的东西，那个net core3.0的winform，有点鸡肋

**Comment by bbhxwl** [comment]
我看到Titanium-Web-Proxy   beta版本也开始支持socks5 了，这就强大了。

**Comment by SmRiley** [comment]
确实是这样,Shadowsocks-windows好像还是用的Framework,但是等到.net 5的话就太久了,(笑,sstap的确是虚拟网卡,目前有另外一个类似项目叫Netch,你可以自己学习看,功能貌似比sstap能强大,并且一直在更新,也是用C#写的.

**Comment by bbhxwl** [comment]
Netch 也能代理电脑全局的么？比如游戏。

**Comment by SmRiley** [comment]
可以

**Comment by bbhxwl** [comment]
我有个项目里面实现了socks5的TCP，但是没实现UDP，我想用你的这个实现UDP。
            UDP_Listen  UDP_Listener = new UDP_Listen(1080);
 直接执行这个代码，不行么？

**Comment by SmRiley** [comment]
> 我有个项目里面实现了socks5的TCP，但是没实现UDP，我想用你的这个实现UDP。
> UDP_Listen UDP_Listener = new UDP_Listen(1080);
> 直接执行这个代码，不行么？

UDP需要基于一条TCP连接,并不是单独的转发实现.

**Comment by bbhxwl** [comment]
哦，好吧，我以为是单独的，那看来还不容易和别的项目整合到一起。
